// Package middleware contains the cross-cutting HTTP middleware used by the
// Mini Fleet Tracker backend (request_id, logger, cors, and — added in
// later tasks — auth, csrf, rate-limit, expiry).
package middleware

import (
	"strings"

	"github.com/gofiber/fiber/v2"
	"github.com/google/uuid"
)

// RequestIDHeader is the canonical HTTP header used to propagate a request
// correlation ID through the system. It is read from the inbound request if
// the client (or an upstream proxy) supplies it; otherwise a fresh value is
// generated by RequestID().
const RequestIDHeader = "X-Request-Id"

// RequestIDLocalsKey is the c.Locals key under which the resolved request ID
// is stored. Downstream middleware (logger, auth) and handlers should read
// it from here rather than re-parsing the header.
const RequestIDLocalsKey = "request_id"

// RequestID returns a Fiber middleware that resolves a request correlation
// ID for every request:
//
//  1. If the inbound X-Request-Id header is present and non-empty (after
//     trimming whitespace), it is reused verbatim — operators frequently
//     inject these from a CDN or load-balancer.
//  2. Otherwise a UUID v4 is minted via google/uuid.
//
// UUID v4 was chosen over v7 to maximise interop with log shippers and
// tooling that still validate the canonical RFC 4122 form; the system has no
// requirement for time-ordering on the request_id (event timestamps already
// provide that).
//
// The resolved value is stashed in c.Locals(RequestIDLocalsKey) for
// downstream consumers and echoed back on the response via
// X-Request-Id so clients can correlate failures with server logs.
//
// This middleware MUST run before middleware.Logger so the per-request
// logger can pick up the request_id.
func RequestID() fiber.Handler {
	return func(c *fiber.Ctx) error {
		id := strings.TrimSpace(c.Get(RequestIDHeader))
		if id == "" {
			id = uuid.NewString()
		}
		c.Locals(RequestIDLocalsKey, id)
		c.Set(RequestIDHeader, id)
		return c.Next()
	}
}

// RequestIDFromCtx returns the request ID stored in c.Locals by RequestID,
// or "" if RequestID has not run (e.g. in tests that bypass the global
// chain). It never panics.
func RequestIDFromCtx(c *fiber.Ctx) string {
	if v, ok := c.Locals(RequestIDLocalsKey).(string); ok {
		return v
	}
	return ""
}
